database:
  mysql:
    dbname: EpicHead
    host: localhost
    password: 123SecurePassword
    port: 3306
    user: root
debug: true
economy:
  currency-name: Oro
  currency-name-plural: Oro
  currency-symbol: $
  decimal-separator: ","
  fraction-digits: 4
  fraction-digits-shown: 2
  grouping-separator: "."
  max-digits-allowed: 13
performance:
  pay-command-only-online: true
  save-db-player-every-transaction: false
  update-player-every-home: false
spawn:
  teleport-on-join: false
  teleport-on-respawn: true
times:
  home:
    cancel-on-move: true
    teleport-delay: 5
  pay:
    cooldown: 5
  spawn:
    cancel-on-move: true
    teleport-delay: 5
  tpa:
    cancel-on-move: true
    expire-petition: 60
    teleport-delay: 5
  warp:
    cancel-on-move: true
    teleport-delay: 5
  back:
    cancel-on-move: true
    teleport-delay: 5
pay:
  minimum-transaction: 0.5
tpa:
  notify-when-req-denied: true
